import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# read file

sales = pd.read_csv(r"C:\data analyst\github\cafe_sales_dirty.csv")

print(sales.head())


# understand data
print(sales.shape)
print(sales.info())
print(sales.describe())


# cleaning data 

print(sales.isnull().sum())

print(sales["Item"].unique())

sales = sales.drop_duplicates(subset="Transaction ID")

sales["Item"] = sales["Item"].replace({"ERROR":pd.NA,"UNKNOWN":pd.NA})
sales["Item"] = sales["Item"].ffill()


sales["Quantity"] = sales["Quantity"].fillna(0)
sales["Quantity"] = sales["Quantity"].replace({"ERROR":0,"UNKNOWN":0})
sales["Quantity"] = sales["Quantity"].astype(int)
sales["Quantity"] = sales["Quantity"].replace(0,pd.NA)
sales["Quantity"] = sales["Quantity"].fillna(sales["Quantity"].mean())

sales["Price Per Unit"] = sales["Price Per Unit"].fillna(0)
sales["Price Per Unit"] = sales["Price Per Unit"].replace({"ERROR":0,"UNKNOWN":0})
sales["Price Per Unit"] = sales["Price Per Unit"].astype(float)
sales["Price Per Unit"] = sales["Price Per Unit"].replace(0,pd.NA)
sales["Price Per Unit"] = sales["Price Per Unit"].fillna(sales["Price Per Unit"].mean())


sales["Total Spent"] = sales["Quantity"]*sales["Price Per Unit"]

sales["Payment Method"] = sales["Payment Method"].replace({"UNKNOWN":pd.NA,"ERROR":pd.NA})
sales["Payment Method"] = sales["Payment Method"].ffill()

sales["Location"] = sales["Location"].replace({"UNKNOWN":pd.NA,"ERROR":pd.NA})
sales["Location"] = sales["Location"].ffill()

sales["Transaction Date"] = sales["Transaction Date"].replace({"UNKNOWN":pd.NA,"ERROR":pd.NA})
sales["Transaction Date"] = sales["Transaction Date"].ffill()
sales["Transaction Date"] = pd.to_datetime(sales["Transaction Date"],format="mixed")


sales["Quantity"] = sales["Quantity"].round().astype(int)
sales["Price Per Unit"] = sales["Price Per Unit"].round(1).astype(float)
sales["Total Spent"] = sales["Total Spent"].round(1).astype(float)


print(sales.head())
print(sales.info())

print(sales.columns)


# What is the total revenue generated?

total_revenue = sales["Total Spent"].sum()

print("total_revenue: ", total_revenue)


# What is the average transaction value?

average_order_value = sales["Total Spent"].mean()

print("average_order_value: ",average_order_value)

# What is the highest transaction amount?

highest_transactions = sales["Total Spent"].max()

print("highest_transactions: ",highest_transactions)

# What is the lowest transaction amount?

lowest_transactions = sales["Total Spent"].min()

print("lowest_transactions: ",lowest_transactions)



# Which item was sold the most?

most_sold_item = sales.groupby("Item")["Quantity"].sum().sort_values(ascending=False).head(1)

print(most_sold_item)

# Which item generated the highest revenue?

highest_revenue_item = sales.groupby("Item")["Total Spent"].sum().sort_values(ascending=False).head(1)

print(highest_revenue_item)


# Top 5 best-selling items.

best_selling_item = sales.groupby("Item")["Quantity"].sum().sort_values(ascending=False).head(5)

print(best_selling_item)

# Bottom 5 least-selling items.

lowest_selling_item = sales.groupby("Item")["Quantity"].sum().sort_values(ascending=False).tail(5)

print(lowest_selling_item)

# Total quantity sold per item.

total_sold_item = sales.groupby("Item")["Quantity"].sum()

print(total_sold_item)



# Which payment method is most frequently used?

payment_method_wise_transaction = sales.groupby("Payment Method")["Transaction ID"].count().sort_values(ascending=False)

print(payment_method_wise_transaction)

# Revenue generated by each payment method.

payment_method_wise_revenue = sales.groupby("Payment Method")["Total Spent"].sum()

print(payment_method_wise_revenue)

# Payment method percentage distribution.

payment_percentage = (
    sales["Payment Method"]
    .value_counts(normalize=True) * 100
)

print(payment_percentage)


# Which location has the highest sales?

location_wise_sale = sales.groupby("Location")["Quantity"].sum()

print(location_wise_sale)


# Which location has the highest number of transactions?


location_wise_transaction = sales.groupby("Location")["Transaction ID"].count()

print(location_wise_transaction)


# Average revenue per location.


average_order_value_per_location = sales.groupby("Location")["Total Spent"].mean()

print(average_order_value_per_location)



# Monthly sales trend.

sales["Year"] = sales["Transaction Date"].dt.year
sales["Month"] = sales["Transaction Date"].dt.month

month_wise_sales = sales.groupby("Month")["Total Spent"].sum()

print(month_wise_sales)

# Daily transaction trend.

daily_transaction = sales.groupby("Transaction Date")["Total Spent"].sum()

print(daily_transaction)

# Best month for sales.

best_month  = sales.groupby("Month")["Total Spent"].sum().sort_values(ascending=False).head(1)

print(best_month)

# Worst month for sales.
worst_month  = sales.groupby("Month")["Total Spent"].sum().sort_values(ascending=False).tail(1)

print(worst_month)







payment_method_wise_transaction = sales.groupby("Payment Method")["Transaction ID"].count().sort_values(ascending=False)

sns.barplot(x="Payment Method",y=sales["Transaction ID"].count(),data=sales)
plt.ylabel("Total Transactions")
plt.title("payment method wise Transactions")
plt.show()

plt.plot(month_wise_sales.index,month_wise_sales.values,marker="o",label="Sales")
plt.xlabel("Months")
plt.ylabel("Total Revenue")
plt.title("Monthly Sales")
plt.grid()
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
plt.bar(best_selling_item.index,best_selling_item.values,label="Sales")
plt.xlabel("Items")
plt.ylabel("Total Quantity")
plt.title("Item by Sales")
plt.legend()
plt.show()


plt.pie(payment_method_wise_revenue.values,labels=payment_method_wise_revenue.index,autopct="%1.1f%%")
plt.title("Payment Method Wise Revenue")
plt.show()

sns.histplot(
    sales["Total Spent"],
    bins=20,
    kde=True
)

plt.show()


sns.boxplot(
    y=sales["Total Spent"]
)

plt.show()



sns.scatterplot(
    x="Quantity",
    y="Total Spent",
    data=sales
)

plt.show()


sns.pairplot(
    sales[
        ["Quantity",
         "Price Per Unit",
         "Total Spent"]
    ]
)

plt.show()